// var s =['apple','banana','strawberry','pineapple'];
// var x = s.slice(0,3)
// console.log(x)
var a = ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','x','y','z']
 a.splice(1,1 )
 a.splice(2,1)
 a.splice(3,1)
 a.splice(4,1)
 a.splice(5,1)
 a.splice(6,1)
 a.splice(7,1)
 a.splice(8,1)
 a.splice(9,1)
 a.splice(10,1)
 a.splice(11,1)
 a.splice(12,1)
 a.splice(13,1)
 a.splice(14,1)
 a.splice(15,1)
 a.splice(16,1)
 a.splice(17,1)
 a.splice(18,1)
 a.splice(19,1)
 a.splice(20,1)
console.log(a)